// src/lib/shopping/priceCatalog.ts

export const PRICE_CATALOG = [
  // Mäso
  {
    match: ["kuracie prsia", "kuracie maso"],
    category: "meat",
    unit: "kg",
    pricePerUnit: 8.49,
    packageSize: 1,
    packageUnit: "kg",
  },
  {
    match: ["kuracie stehna", "kuracie stehno"],
    category: "meat",
    unit: "kg",
    pricePerUnit: 5.49,
    packageSize: 1,
    packageUnit: "kg",
  },
  {
    match: ["morcacie prsia"],
    category: "meat",
    unit: "kg",
    pricePerUnit: 9.99,
    packageSize: 1,
    packageUnit: "kg",
  },
  {
    match: ["bravcove maso"],
    category: "meat",
    unit: "kg",
    pricePerUnit: 7.49,
    packageSize: 1,
    packageUnit: "kg",
  },
  {
    match: ["bravcova panenka"],
    category: "meat",
    unit: "kg",
    pricePerUnit: 12.99,
    packageSize: 0.5,
    packageUnit: "kg",
  },
  {
    match: ["hovadzie maso"],
    category: "meat",
    unit: "kg",
    pricePerUnit: 14.99,
    packageSize: 0.5,
    packageUnit: "kg",
  },
  {
    match: ["mlete maso"],
    category: "meat",
    unit: "kg",
    pricePerUnit: 8.99,
    packageSize: 0.5,
    packageUnit: "kg",
  },
  {
    match: ["slanina"],
    category: "meat",
    unit: "kg",
    pricePerUnit: 11.99,
    packageSize: 0.2,
    packageUnit: "kg",
  },
  {
    match: ["salama"],
    category: "meat",
    unit: "kg",
    pricePerUnit: 13.99,
    packageSize: 0.15,
    packageUnit: "kg",
  },
  {
    match: ["sunka"],
    category: "meat",
    unit: "kg",
    pricePerUnit: 12.49,
    packageSize: 0.15,
    packageUnit: "kg",
  },

  // Ryby
  {
    match: ["losos"],
    category: "fish",
    unit: "kg",
    pricePerUnit: 18.99,
    packageSize: 0.25,
    packageUnit: "kg",
  },
  {
    match: ["tuniak"],
    category: "fish",
    unit: "ks",
    pricePerUnit: 2.49,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["treska"],
    category: "fish",
    unit: "kg",
    pricePerUnit: 11.99,
    packageSize: 0.4,
    packageUnit: "kg",
  },

  // Mliečne výrobky
  {
    match: ["mlieko"],
    category: "dairy",
    unit: "l",
    pricePerUnit: 1.29,
    packageSize: 1,
    packageUnit: "l",
  },
  {
    match: ["smotana"],
    category: "dairy",
    unit: "ks",
    pricePerUnit: 1.19,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["jogurt"],
    category: "dairy",
    unit: "ks",
    pricePerUnit: 0.79,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["grecky jogurt"],
    category: "dairy",
    unit: "ks",
    pricePerUnit: 1.49,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["tvaroh"],
    category: "dairy",
    unit: "ks",
    pricePerUnit: 1.59,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["maslo"],
    category: "dairy",
    unit: "ks",
    pricePerUnit: 2.99,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["syr"],
    category: "dairy",
    unit: "kg",
    pricePerUnit: 13.99,
    packageSize: 0.2,
    packageUnit: "kg",
  },
  {
    match: ["eidam"],
    category: "dairy",
    unit: "kg",
    pricePerUnit: 10.99,
    packageSize: 0.2,
    packageUnit: "kg",
  },
  {
    match: ["mozzarella"],
    category: "dairy",
    unit: "ks",
    pricePerUnit: 1.09,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["parmezan"],
    category: "dairy",
    unit: "kg",
    pricePerUnit: 22.99,
    packageSize: 0.1,
    packageUnit: "kg",
  },

  // Vajcia
  {
    match: ["vajcia"],
    category: "dairy",
    unit: "ks",
    pricePerUnit: 0.27,
    packageSize: 10,
    packageUnit: "ks",
  },

  // Pečivo
  {
    match: ["chlieb"],
    category: "bakery",
    unit: "ks",
    pricePerUnit: 2.19,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["toastovy chlieb"],
    category: "bakery",
    unit: "ks",
    pricePerUnit: 1.89,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["rozok"],
    category: "bakery",
    unit: "ks",
    pricePerUnit: 0.18,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["bageta"],
    category: "bakery",
    unit: "ks",
    pricePerUnit: 1.49,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["tortilla"],
    category: "bakery",
    unit: "balenie",
    pricePerUnit: 2.49,
    packageSize: 1,
    packageUnit: "balenie",
  },

  // Prílohy
  {
    match: ["ryza"],
    category: "grains",
    unit: "kg",
    pricePerUnit: 2.79,
    packageSize: 0.5,
    packageUnit: "kg",
  },
  {
    match: ["cestoviny"],
    category: "grains",
    unit: "kg",
    pricePerUnit: 2.49,
    packageSize: 0.5,
    packageUnit: "kg",
  },
  {
    match: ["spagety"],
    category: "grains",
    unit: "kg",
    pricePerUnit: 2.29,
    packageSize: 0.5,
    packageUnit: "kg",
  },
  {
    match: ["zemiaky"],
    category: "vegetable",
    unit: "kg",
    pricePerUnit: 1.49,
    packageSize: 2,
    packageUnit: "kg",
  },
  {
    match: ["bataty"],
    category: "vegetable",
    unit: "kg",
    pricePerUnit: 3.49,
    packageSize: 1,
    packageUnit: "kg",
  },
  {
    match: ["kuskus"],
    category: "grains",
    unit: "kg",
    pricePerUnit: 4.49,
    packageSize: 0.5,
    packageUnit: "kg",
  },
  {
    match: ["quinoa"],
    category: "grains",
    unit: "kg",
    pricePerUnit: 7.99,
    packageSize: 0.25,
    packageUnit: "kg",
  },
  {
    match: ["bulgur"],
    category: "grains",
    unit: "kg",
    pricePerUnit: 4.99,
    packageSize: 0.5,
    packageUnit: "kg",
  },

  // Zelenina
  {
    match: ["mrkva"],
    category: "vegetable",
    unit: "kg",
    pricePerUnit: 1.49,
    packageSize: 1,
    packageUnit: "kg",
  },
  {
    match: ["cibula"],
    category: "vegetable",
    unit: "kg",
    pricePerUnit: 1.69,
    packageSize: 1,
    packageUnit: "kg",
  },
  {
    match: ["cesnak"],
    category: "vegetable",
    unit: "kg",
    pricePerUnit: 6.99,
    packageSize: 0.1,
    packageUnit: "kg",
  },
  {
    match: ["paradajky"],
    category: "vegetable",
    unit: "kg",
    pricePerUnit: 3.49,
    packageSize: 0.5,
    packageUnit: "kg",
  },
  {
    match: ["cherry paradajky"],
    category: "vegetable",
    unit: "kg",
    pricePerUnit: 5.99,
    packageSize: 0.25,
    packageUnit: "kg",
  },
  {
    match: ["uhorka"],
    category: "vegetable",
    unit: "ks",
    pricePerUnit: 1.19,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["paprika"],
    category: "vegetable",
    unit: "kg",
    pricePerUnit: 4.99,
    packageSize: 0.5,
    packageUnit: "kg",
  },
  {
    match: ["brokolica"],
    category: "vegetable",
    unit: "ks",
    pricePerUnit: 1.99,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["karfiol"],
    category: "vegetable",
    unit: "ks",
    pricePerUnit: 2.49,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["spenat"],
    category: "vegetable",
    unit: "balenie",
    pricePerUnit: 1.89,
    packageSize: 1,
    packageUnit: "balenie",
  },

  // Ovocie
  {
    match: ["banany"],
    category: "fruit",
    unit: "kg",
    pricePerUnit: 1.99,
    packageSize: 1,
    packageUnit: "kg",
  },
  {
    match: ["jablka"],
    category: "fruit",
    unit: "kg",
    pricePerUnit: 2.49,
    packageSize: 1,
    packageUnit: "kg",
  },
  {
    match: ["pomarance"],
    category: "fruit",
    unit: "kg",
    pricePerUnit: 2.79,
    packageSize: 1,
    packageUnit: "kg",
  },
  {
    match: ["mandarinky"],
    category: "fruit",
    unit: "kg",
    pricePerUnit: 2.99,
    packageSize: 1,
    packageUnit: "kg",
  },
  {
    match: ["citron"],
    category: "fruit",
    unit: "kg",
    pricePerUnit: 3.49,
    packageSize: 0.5,
    packageUnit: "kg",
  },
  {
    match: ["limetka"],
    category: "fruit",
    unit: "kg",
    pricePerUnit: 5.99,
    packageSize: 0.25,
    packageUnit: "kg",
  },
  {
    match: ["jahody"],
    category: "fruit",
    unit: "kg",
    pricePerUnit: 7.99,
    packageSize: 0.5,
    packageUnit: "kg",
  },
  {
    match: ["maliny"],
    category: "fruit",
    unit: "kg",
    pricePerUnit: 14.99,
    packageSize: 0.125,
    packageUnit: "kg",
  },
  {
    match: ["borovky"],
    category: "fruit",
    unit: "kg",
    pricePerUnit: 11.99,
    packageSize: 0.125,
    packageUnit: "kg",
  },
  {
    match: ["hrozno"],
    category: "fruit",
    unit: "kg",
    pricePerUnit: 3.99,
    packageSize: 0.5,
    packageUnit: "kg",
  },

  // Konzervy a trvanlivé
  {
    match: ["fazula"],
    category: "legumes",
    unit: "ks",
    pricePerUnit: 1.29,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["cicer"],
    category: "legumes",
    unit: "ks",
    pricePerUnit: 1.39,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["sosovica"],
    category: "legumes",
    unit: "kg",
    pricePerUnit: 3.49,
    packageSize: 0.5,
    packageUnit: "kg",
  },
  {
    match: ["paradajkovy pretlak"],
    category: "pantry",
    unit: "ks",
    pricePerUnit: 1.19,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["kokosove mlieko"],
    category: "pantry",
    unit: "ks",
    pricePerUnit: 2.29,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["tuniak v konzerve"],
    category: "fish",
    unit: "ks",
    pricePerUnit: 2.49,
    packageSize: 1,
    packageUnit: "ks",
  },

  // Oleje a dochucovadlá
  {
    match: ["olivovy olej"],
    category: "pantry",
    unit: "l",
    pricePerUnit: 9.99,
    packageSize: 0.5,
    packageUnit: "l",
  },
  {
    match: ["slnecnicovy olej"],
    category: "pantry",
    unit: "l",
    pricePerUnit: 2.99,
    packageSize: 1,
    packageUnit: "l",
  },
  {
    match: ["sol"],
    category: "pantry",
    unit: "kg",
    pricePerUnit: 0.89,
    packageSize: 1,
    packageUnit: "kg",
  },
  {
    match: ["cierne korenie"],
    category: "pantry",
    unit: "ks",
    pricePerUnit: 1.99,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["oregano"],
    category: "pantry",
    unit: "ks",
    pricePerUnit: 0.99,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["bazalka"],
    category: "pantry",
    unit: "ks",
    pricePerUnit: 1.09,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["paprika korenie"],
    category: "pantry",
    unit: "ks",
    pricePerUnit: 1.29,
    packageSize: 1,
    packageUnit: "ks",
  },

  // Sladké a raňajky
  {
    match: ["ovsenne vlocky"],
    category: "breakfast",
    unit: "kg",
    pricePerUnit: 2.49,
    packageSize: 0.5,
    packageUnit: "kg",
  },
  {
    match: ["musli"],
    category: "breakfast",
    unit: "kg",
    pricePerUnit: 5.99,
    packageSize: 0.5,
    packageUnit: "kg",
  },
  {
    match: ["med"],
    category: "breakfast",
    unit: "kg",
    pricePerUnit: 8.99,
    packageSize: 0.5,
    packageUnit: "kg",
  },
  {
    match: ["arasidove maslo"],
    category: "breakfast",
    unit: "ks",
    pricePerUnit: 4.99,
    packageSize: 1,
    packageUnit: "ks",
  },
  {
    match: ["nutella"],
    category: "breakfast",
    unit: "ks",
    pricePerUnit: 5.49,
    packageSize: 1,
    packageUnit: "ks",
  },

  // Nápoje
  {
    match: ["mineralka"],
    category: "drinks",
    unit: "l",
    pricePerUnit: 0.69,
    packageSize: 1.5,
    packageUnit: "l",
  },
  {
    match: ["dzus"],
    category: "drinks",
    unit: "l",
    pricePerUnit: 2.19,
    packageSize: 1,
    packageUnit: "l",
  },
  {
    match: ["cola"],
    category: "drinks",
    unit: "l",
    pricePerUnit: 1.79,
    packageSize: 1.5,
    packageUnit: "l",
  },
  {
    match: ["kava"],
    category: "drinks",
    unit: "kg",
    pricePerUnit: 18.99,
    packageSize: 0.25,
    packageUnit: "kg",
  },
  {
    match: ["caj"],
    category: "drinks",
    unit: "ks",
    pricePerUnit: 2.49,
    packageSize: 1,
    packageUnit: "ks",
  },
];